### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Vjacheslav250/-Grid-template#1]
1)
кнопки отсуствуют
![image](https://user-images.githubusercontent.com/8464662/120932617-339fc180-c6ff-11eb-83ff-a435d8a0b49a.png)

2)
меню не работает
![image](https://user-images.githubusercontent.com/8464662/120932664-5e8a1580-c6ff-11eb-93e5-0d683baba908.png)

**Comment by Vjacheslav250** [comment]
Доброй ночи, Alecto!
Я исправил эти ошибки, вроде всё работает!

**Comment by Alecto** [comment]
две ссылочки пожалуйста

пн, 7 июн. 2021 г. в 00:12, Vjacheslav250 ***@***.***>:

**Comment by Vjacheslav250** [comment]
Ok!
https://github.com/Vjacheslav250/-Grid-template
https://vjacheslav250.github.io/-Grid-template/

**Comment by Alecto** [comment]
отлично, работа принята.
в переписке через гитхаб потерялась инфа, кому ставить.
Вячеслав Пометун , правильно?

пн, 7 июн. 2021 г. в 09:39, Vjacheslav250 ***@***.***>:

**Comment by Vjacheslav250** [comment]
Да, да!
Пометун Вячеслав!
Спасибо Вам большое, Андрей!
